name: Locksmithy
version: @version@ # version specified by gradle configuration
main: com.makotomiyamoto.locksmithyv2.LocksmithyPlugin
api-version: 1.16
commands:
  ploc:
    usage: Get location of player
    permission: locksmithy.admin
